stages:
  - build

build_image:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind 
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  stage: build
  before_script:
    - docker login -u harshitkh1 -p $DOCKER_PAT 
  script:
    - docker build ./backend -t harshitkh1/todo_gitlab:backend
    - docker build ./frontend -t harshitkh1/todo_gitlab:frontend 
    - docker push harshitkh1/todo_gitlab:backend
    - docker push harshitkh1/todo_gitlab:frontend
